import Goal from "./OurGoal";
import Grow from "./Grow";
import Members from "./Members";
import Problem from "./Problem";

export const metadata = {
  title: "About | DWM",
  description: "Generated by create next app",
};
const data = [
  {
    name: "Iqbal Hossain",
    title: "Backed Engineer",
    image: "/images/profile.jpg",
  },
  {
    name: "Mehedi hassan",
    title: "UI Expert",
    image: "/images/profile.jpg",
  },
  {
    name: "Salman",
    title: "Full stack developer",
    image: "/images/profile.jpg",
  },
];
const AboutPage = () => {
  return (
    <>
      <Goal></Goal>
      <Problem></Problem>
      <Grow></Grow>
    </>
  );
};

export default AboutPage;
