import teamMembers from '@/app/data/teamMembers';
import Image from 'next/image';
import React from 'react';
import Cart from './Cart';
import aboutPageData from '@/app/data/aboutPageData';
import DesignCard from './DesignCard';
import Link from 'next/link';


export const metadata = {
    title: 'about | Next App',
    description: 'Generated by create next app',
  }
  const AboutPage = () => {
    return (
       <>
       <div className=' flex justify-center  '>
         <div  className='w-4/5'>
     <div className='pt-4  '>
 
               <h2 className='font-bold text-4xl text-red-500  text-center '>About <span className='text-blue-500'>Us</span></h2>
               <p className='text-center text-gray-500 py-4 '> At Dream Web Market, our turn your ideas into <br /> awesome websites. 
               Whether</p>
             <div className=' pt-2 flex justify-center'>
             <Image src="/images/about-img.jpg" width={700} height={700} alt="Member Image" className="  rounded-lg"/>
             </div>
               <div className=' font-semibold text-base text-left py-4'>
            <p>   At Dream Web Market, our mission is simple: turn your ideas into awesome websites. 
               Whether you are starting a business, expressing your </p>
            
           <p className='py-2 text-gradient'>
  You we are here to make your online dreams come true. We blend creativity and the latest tech
                 to create websites that stand out.</p>
              
              <p>  Think of us as your digital partners, committed to
                  understanding and bringing your unique vision to life. Customer happiness is our priority,</p> 
              
                  <p className='pt-2'>and we are not just a service; we are here to propel you to success in the digital world.
                Dream big, dream online Dream Web Market is your ticket to a fantastic digital future
                to a fantastic digital future</p>
               </div>

          </div>
            

          <div className=' py-8'>
 
          
          <h2 className='font-bold text-4xl text-red-500  text-center '>Meet Our <span className='text-blue-500'>Team</span></h2>
               <p className='text-center text-gray-500 py-4 '> At Dream Web Market, our turn your ideas into <br /> awesome websites. 
               Whether</p>
<div className='grid grid-cols-1 md:grid-cols-4 gap-4 pt-8 pb-8'>
{
    teamMembers.map(member =><Cart key={member.id } members={member}></Cart> )
}
</div>

</div>


<div className=' pb-4  text-center'>
 
 <h2 className='font-bold text-4xl  text-red-500  text-center  '>Join Our <span className='text-blue-500'>Team</span></h2>
 <p className='text-center text-gray-500 py-4  mb-2'> At Dream Web Market, our turn your ideas into <br /> awesome websites. 
               Whether</p>

<Link href={'/contact'} className='apply-button   text-center'> Apply</Link>


<div className='grid grid-cols-1 md:grid-cols-2 gap-4 pt-8 pb-8'>
{
aboutPageData.map(data =><DesignCard key={data.id } data={data}></DesignCard> )
}
</div>

</div>

        </div>
       </div>
       <div className=' relative '>
        <div className=' absolute  bg-black  top-0 bottom-0 left-0  right-0 opacity-60 rounded-lg'></div>
       <div className='  flex justify-center  w-full  h-56'>
             <Image src="/images/about-img-2.jpg" width={1000} height={300} alt="Member Image" className="  rounded-lg"/>
             </div>
           <div className=' flex justify-center items-center absolute   top-0 left-0  bottom-0 right-0 font-semibold text-3xl text-white'>
           <div>
           <h2  className=' '>Start talking with us</h2>
            <Link href={"/"} className='bg-blue-500 px-5 py-2  capitalize rounded-full font-semibold text-lg text-white'>Contact us</Link>
         
           </div>
             </div>
       </div>
       </>
    );
};

export default AboutPage;