import React from 'react';


export const metadata = {
    title: 'profile | Next App',
    description: 'Generated by create next app',
  }
const page = () => {
    return (
        <div>
            <h1 className=' text-red-900'>profile page</h1>
        </div>
    );
};

export default page;