
import ContactForm from '@/app/components/contactForm';
import CopyButton from '@/app/components/copyButton';
import Image from 'next/image';
import React from 'react';



export const metadata = {
    title: 'contact | Next App',
    description: 'Generated by create next app',
  }
  const AboutPage = () => {
    return (
        <div>
      


          <div
    className="   h-screen  relative    bg-no-repeat  bg-right-bottom bg-cover"
    style={{
      backgroundImage: 'url("https://media.istockphoto.com/id/1688578381/photo/contact-us-telephone-envelope-letter-and-e-mail-symbols-on-wooden-round-in-row-on-table-with.webp?b=1&s=170667a&w=0&k=20&c=FaGQdXfMLV6SgHLLG70p41UkUocD0G7831VeLY1B0WI=")', // Replace with your actual image URL
     
      backgroundAttachment: 'fixed', 
    }}
  >
      <div className=' absolute    z-0   top-0 left-0 right-0 bottom-0 bg-black  opacity-60  text-white'>

      </div>
      
      <div className=' absolute  z-20 right-0 left-0   top-10 '>
      <div className='pt-4'>
      <h2 className='font-bold text-4xl text-red-500  text-center  '>Contact <span className='text-blue-500'>Us</span></h2>
 
<div className='grid grid-cols-3'>
<div className=' col-span-1 '>
<div className='flex justify-center items-center'>
<div className='bg-white  rounded  py-6 px-2 mt-16 '>
<div className='flex justify-between items-center  border-y border-red-300  bg-white   text-white'>
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 99.59 99.59" id="linkedin-circle"><defs><linearGradient id="a" x1="-1.971" x2="-1.264" y1="2.61" y2="3.317" gradientUnits="objectBoundingBox"><stop offset="0" ></stop><stop offset="1" ></stop></linearGradient></defs><path fill="url(#a)" d="M56.82,7.025a49.795,49.795,0,1,0,49.8,49.795A49.795,49.795,0,0,0,56.82,7.025ZM43.534,80.893H32.6V45.572H43.534ZM38.016,40.946a6.518,6.518,0,1,1,6.465-6.517A6.492,6.492,0,0,1,38.016,40.946Zm46.49,39.947H73.626V62.353c0-5.085-1.932-7.924-5.953-7.924-4.376,0-6.662,2.956-6.662,7.924V80.893H50.525V45.572H61.011v4.757a12.319,12.319,0,0,1,10.644-5.835c7.49,0,12.851,4.573,12.851,14.034V80.893Z" data-name="linkedin circle" transform="translate(-7.025 -7.025)">
</path>
</svg>
<h2 className=' text-black  px-2'>99999999999</h2>
<CopyButton textToCopy={"99999999999"} />
</div>
<div className='flex justify-between items-center    text-white'>
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 99.59 99.59" id="linkedin-circle"><defs><linearGradient id="a" x1="-1.971" x2="-1.264" y1="2.61" y2="3.317" gradientUnits="objectBoundingBox"><stop offset="0" ></stop><stop offset="1" ></stop></linearGradient></defs><path fill="url(#a)" d="M56.82,7.025a49.795,49.795,0,1,0,49.8,49.795A49.795,49.795,0,0,0,56.82,7.025ZM43.534,80.893H32.6V45.572H43.534ZM38.016,40.946a6.518,6.518,0,1,1,6.465-6.517A6.492,6.492,0,0,1,38.016,40.946Zm46.49,39.947H73.626V62.353c0-5.085-1.932-7.924-5.953-7.924-4.376,0-6.662,2.956-6.662,7.924V80.893H50.525V45.572H61.011v4.757a12.319,12.319,0,0,1,10.644-5.835c7.49,0,12.851,4.573,12.851,14.034V80.893Z" data-name="linkedin circle" transform="translate(-7.025 -7.025)">
</path>
</svg>
<h2 className='text-black  px-2'>mail@gmail.com</h2>
<CopyButton textToCopy={"mail@gmail.com"} />
</div>
<div className='flex  justify-between items-center  border-y border-red-300 text-white'>
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 99.59 99.59" id="linkedin-circle"><defs><linearGradient id="a" x1="-1.971" x2="-1.264" y1="2.61" y2="3.317" gradientUnits="objectBoundingBox"><stop offset="0" ></stop><stop offset="1" ></stop></linearGradient></defs><path fill="url(#a)" d="M56.82,7.025a49.795,49.795,0,1,0,49.8,49.795A49.795,49.795,0,0,0,56.82,7.025ZM43.534,80.893H32.6V45.572H43.534ZM38.016,40.946a6.518,6.518,0,1,1,6.465-6.517A6.492,6.492,0,0,1,38.016,40.946Zm46.49,39.947H73.626V62.353c0-5.085-1.932-7.924-5.953-7.924-4.376,0-6.662,2.956-6.662,7.924V80.893H50.525V45.572H61.011v4.757a12.319,12.319,0,0,1,10.644-5.835c7.49,0,12.851,4.573,12.851,14.034V80.893Z" data-name="linkedin circle" transform="translate(-7.025 -7.025)">
</path>
</svg>
<h2 className='text-black  px-2'>Facebook Link</h2>
<CopyButton textToCopy={"https://www.facebook.com/profile.php?id=61554824227057"} />
</div>
</div>
</div>
<div className='flex py-2  mt-6 justify-center items-end'>
<h2 className='  font-semibold text-white'>Please connect</h2>
<a className='px-1' href="https://www.facebook.com/YourPageURL" target="_blank" rel="noopener noreferrer">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="126.445 2.281 589 589" id="facebook">
<circle cx="420.945" cy="296.781" r="294.5" fill="#3c5a9a"></circle>
<path fill="#fff" d="M516.704 92.677h-65.239c-38.715 0-81.777 16.283-81.777 72.402.189 19.554 0 38.281 0 59.357H324.9v71.271h46.174v205.177h84.847V294.353h56.002l5.067-70.117h-62.531s.14-31.191 0-40.249c0-22.177 23.076-20.907 24.464-20.907 10.981 0 32.332.032 37.813 0V92.677h-.032z">
</path>
</svg>
</a>

<a className='px-1' href=""><svg xmlns="http://www.w3.org/2000/svg" width="24" height="26" viewBox="0 0 224 226" id="facebook-messenger"><defs><linearGradient id="a" x1="50%" x2="50%" y1="6.76%" y2="95.6%"><stop offset="0" ></stop><stop offset="1" ></stop></linearGradient></defs><path fill="url(#a)" d="m41.255 185.52v40.2l37.589-21.37c10.478 3.02 21.616 4.65 33.156 4.65 61.86 0 112-46.79 112-104.5 0-57.714-50.14-104.5-112-104.5-61.856 0-112 46.786-112 104.5 0 32.68 16.078 61.86 41.255 81.02z"></path><path fill="#fff" d="m100.04 75.878l-60.401 63.952 54.97-30.16 28.721 30.16 60.06-63.952-54.36 29.632-28.99-29.632z"></path></svg>
</a>
<a className='' href="">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 99.59 99.59" id="linkedin-circle"><defs><linearGradient id="a" x1="-1.971" x2="-1.264" y1="2.61" y2="3.317" gradientUnits="objectBoundingBox"><stop offset="0" ></stop><stop offset="1" ></stop></linearGradient></defs><path fill="url(#a)" d="M56.82,7.025a49.795,49.795,0,1,0,49.8,49.795A49.795,49.795,0,0,0,56.82,7.025ZM43.534,80.893H32.6V45.572H43.534ZM38.016,40.946a6.518,6.518,0,1,1,6.465-6.517A6.492,6.492,0,0,1,38.016,40.946Zm46.49,39.947H73.626V62.353c0-5.085-1.932-7.924-5.953-7.924-4.376,0-6.662,2.956-6.662,7.924V80.893H50.525V45.572H61.011v4.757a12.319,12.319,0,0,1,10.644-5.835c7.49,0,12.851,4.573,12.851,14.034V80.893Z" data-name="linkedin circle" transform="translate(-7.025 -7.025)">
</path>
</svg>
</a>
</div>
</div>
<div className=' col-span-2 '>
<div className=' '>
<ContactForm></ContactForm>
</div>
   </div>
</div> 
</div>
          </div>
      
          </div>


         
            

  

        </div>
    );
};

export default AboutPage;

  {/* backgroundImage: 'url("https://media.istockphoto.com/id/1688578381/photo/contact-us-telephone-envelope-letter-and-e-mail-symbols-on-wooden-round-in-row-on-table-with.webp?b=1&s=170667a&w=0&k=20&c=FaGQdXfMLV6SgHLLG70p41UkUocD0G7831VeLY1B0WI=")', */}

       