import ContactForm from "@/app/components/contactForm";
import CopyButton from "@/app/components/copyButton";

import Link from "next/link";
import React from "react";

export const metadata = {
  title: "contact | Next App",
  description: "Generated by create next app",
};

const AboutPage = () => {
  return (
    <div>
      <div className="         ">
        <div className="   top-10 ">
          <div className="pt-4">
            <h2 className="font-bold text-2xl md:text-4xl text-red-500  text-center  pt-5 pb-12">
              <span className=" ">Get in</span>{" "}
              <span className="text-blue-500  ">Touch</span>
            </h2>

            <div className="grid  grid-cols-1 md:grid-cols-5 gap-5 ">
              <div className=" col-span-2 w-full">
                <div className="w-full bg-white py-4 border rounded-md flex flex-col gap-4 px-3 md:px-7">
                  <div className="flex justify-between items-center  border-b-2   p-3 shadow rounded-lg text-white">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      viewBox="0 0 32 32"
                      width="24"
                      height="24"
                      id="phone"
                    >
                      <path
                        fill="black"
                        d="M27.308,20.649l-2.2-2.2a3.521,3.521,0,0,0-4.938-.021,2.152,2.152,0,0,1-2.729.267A15.026,15.026,0,0,1,13.3,14.562a2.181,2.181,0,0,1,.284-2.739A3.521,3.521,0,0,0,13.553,6.9l-2.2-2.2a3.514,3.514,0,0,0-4.961,0l-.633.634c-3.3,3.3-3.053,10.238,3.813,17.1,4.14,4.141,8.307,5.875,11.686,5.875a7.5,7.5,0,0,0,5.418-2.061l.634-.634A3.513,3.513,0,0,0,27.308,20.649ZM25.894,24.2l-.634.634c-2.6,2.6-8.339,2.125-14.276-3.813S4.571,9.34,7.171,6.74L7.8,6.107a1.511,1.511,0,0,1,2.133,0l2.2,2.2a1.511,1.511,0,0,1,.021,2.11,4.181,4.181,0,0,0-.531,5.239,17.01,17.01,0,0,0,4.713,4.706,4.179,4.179,0,0,0,5.231-.517,1.512,1.512,0,0,1,2.118.013l2.2,2.2A1.51,1.51,0,0,1,25.894,24.2Z"
                      ></path>
                    </svg>
                    <h2 className="text-black bg-gray-50 overflow-hidden p-1  px-2">
                      +880-1677176199
                    </h2>
                    <CopyButton textToCopy={"+880-1677176199"} />
                  </div>
                  <div className="flex justify-between items-center  border-b-2   p-3 shadow rounded-lg text-white">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      x="0px"
                      y="0px"
                      width="24"
                      height="24"
                      viewBox="0 0 48 48"
                    >
                      <path
                        fill="#4caf50"
                        d="M45,16.2l-5,2.75l-5,4.75L35,40h7c1.657,0,3-1.343,3-3V16.2z"
                      ></path>
                      <path
                        fill="#1e88e5"
                        d="M3,16.2l3.614,1.71L13,23.7V40H6c-1.657,0-3-1.343-3-3V16.2z"
                      ></path>
                      <polygon
                        fill="#e53935"
                        points="35,11.2 24,19.45 13,11.2 12,17 13,23.7 24,31.95 35,23.7 36,17"
                      ></polygon>
                      <path
                        fill="#c62828"
                        d="M3,12.298V16.2l10,7.5V11.2L9.876,8.859C9.132,8.301,8.228,8,7.298,8h0C4.924,8,3,9.924,3,12.298z"
                      ></path>
                      <path
                        fill="#fbc02d"
                        d="M45,12.298V16.2l-10,7.5V11.2l3.124-2.341C38.868,8.301,39.772,8,40.702,8h0 C43.076,8,45,9.924,45,12.298z"
                      ></path>
                    </svg>
                    <h2 className="text-black bg-gray-50 overflow-hidden p-1  px-2">
                      web.salman.pro@gmail.com
                    </h2>
                    <CopyButton textToCopy={"web.salman.pro@gmail.com"} />
                  </div>
                  <div className="flex justify-between items-center  border-b-2   p-3 shadow rounded-lg text-white">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="24"
                      height="24"
                      viewBox="126.445 2.281 589 589"
                      id="facebook"
                    >
                      <circle
                        cx="420.945"
                        cy="296.781"
                        r="294.5"
                        fill="#fff"
                      ></circle>
                      <path
                        fill="blue"
                        d="M516.704 92.677h-65.239c-38.715 0-81.777 16.283-81.777 72.402.189 19.554 0 38.281 0 59.357H324.9v71.271h46.174v205.177h84.847V294.353h56.002l5.067-70.117h-62.531s.14-31.191 0-40.249c0-22.177 23.076-20.907 24.464-20.907 10.981 0 32.332.032 37.813 0V92.677h-.032z"
                      ></path>
                    </svg>
                    <h2 className="text-black bg-gray-50 overflow-hidden p-1  px-2">
                      Facebook Page
                    </h2>
                    <div className="justify-self-end">
                      <Link
                        href={
                          "https://web.facebook.com/people/Dream-Web-Market/61554824227057/"
                        }
                        target="_blank"
                        className={`copy-button text-blue-500
                          border-b-2  border-blue-500  px-2 py-1 rounded`}
                      >
                        LINK
                      </Link>
                    </div>
                  </div>
                </div>
              </div>
              <div className=" col-span-3 w-full  ">
                <div className="mb-8 ">
                  <ContactForm></ContactForm>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default AboutPage;
