import Link from 'next/link';
import React from 'react';
export const metadata = {
    title: 'blog | Next App',
    description: 'Generated by create next app',
  }
const Blogpage = () => {

    const blogs = [

        {
            id:1,
            year: 2000,
            title: "title 1"
        },
        {
            id:2,
            year: 2000,
            title: "title 2"
        },
        {
            id:3,
            year: 2000,
            title: "title 3"
        },
        {
            id:4,
            year: 2000,
            title: "title 4"
        }
    ]

    // href={`/blogs2/${year}/${id}`}
    return (
        <div className='container mx-auto'>
            {
                blogs.map(({id, year, title})=>
                <Link 
                className='block border border-red-600 '
                href={{
                    pathname: `/blogs2/${year}/${id}`,
                    query:{
                        title: title,
                    }
                }}
                
                key={id}>
                    {title}
                    </Link>
                    )
                
            }
        </div>
    );
};

export default Blogpage;