import React from 'react';

export const metadata = {
    title: 'dashboard | Next App',
    description: 'Generated by create next app',
  }
const page = () => {
    return (
        <div>
            <h2>dashboard page</h2>
        </div>
    );
};

export default page;